### ISSUE TITLE
Wrong dependency on glite-yaim-bdii in Debian

### ISSUE THREAD

**Issue by valtri** [CESNET/glite-lb#13]
Enol Fernández wrote:

> I found another issue with the L&B. When the system tries to fetch the 
> packages there is a missing dependency:
> 
> The following packages have unmet dependencies:
>   glite-lb-yaim : Depends: glite-yaim-bdii but it is not installable
>  E: Broken packages
> 
> I have not seen glite-yaim-bdii anywhere in EMI-3 debian repo.

**Comment by valtri** [comment]
Already fixed but not released in EMI-3 update 3.

**Comment by sustr4** [comment]
The fix has been released.
