### ISSUE TITLE
Maven pom files for java modules

### ISSUE THREAD

**Issue by valtri** [CESNET/glite-lb#18]
https://bugzilla.redhat.com/show_bug.cgi?id=965848 (review request of glite-jobid-api-java):

You might want to consider adding a pom file and generating a maven
dependency map to the installed package so that it can be used a
buildrequires for other packages that build using maven, even if this
package itself is built using ant. (This is however not mandatory
according to the guidelines, since upstream does not provide a pom
file. You might get a feature request filed against the package later
asking for it - I have gotten such requests for java packages I
packaged before.)

There are such users, as can be seen e.g. in
https://github.com/italiangrid/cream-parent/blob/master/pom.xml:

```
  <dependency>
    <groupId>org.glite.lb</groupId>
    <artifactId>jobid-api-java</artifactId>
    <version>1.3.4</version>
    <scope>compile</scope>
  </dependency>
```

**Comment by sustr4** [comment]
Change handed over for release
