### ISSUE TITLE
LB deployment scripts do not support non-default DB locations

### ISSUE THREAD

**Issue by sustr4** [CESNET/glite-lb#22]
LB deployment scripts fail in case site administrator has changed LB server's database location. This should be either fixed, or at least documented.

**Comment by valtri** [comment]
It's harder than it looked like at the first sight.

The first problem is "escaping hell" - variables in shell for using as arguments can't contain spaces (which is also the current issue - with MYSQL_PASSWORD). Bash could help with that with arrays, but in the end I just used separate variables for passwords. MySQL argument --password="$PASS" accepts empty variable and shell permits there a variable with spaces.

The second problem are various consequences of supporting any DB connection - perform the setup of the local database service if there is specified remote server? Also it is needed to connect on the same host for both admin and user access to the database.

And it requires thorough testing (various platforms, upgrades, yaim vs glite-lb-setup, special characters, ...).

But I think the official support would be useful:
- bkserverd machine may be need to separate from database machine
- admins may want to setup user password for the local DB connection
